name: Python Test
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
jobs:
  test:
    name: Python ${{ python_version }} Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ python_version }}
      - run: pip install -r requirements_dev.txt
      - run: python setup.py develop
      - run: ruff .
      - run: pytest